/**
 * ERZEUGT — nicht von Hand ändern. Quelle: servers/sevdesk/schema/sevdesk-api.json,
 * erzeugt von scripts/gen-sevdesk-api.mjs.
 *
 * github.com/nikolausm/mcp-sevdesk, openapi/sevdesk-openapi.yaml
 * eingefroren am 2026-08-10, Commit e6769c878ffe8591e2509ccb66837cc0e1b2890e
 *
 * Schlüssel ist "METHODE /Pfad" mit den Platzhaltern der Beschreibung, also
 * "GET /Invoice/{invoiceId}". p = Pfadparameter, q = Query-Parameter (t = Typ,
 * e = erlaubte Werte, r = Pflicht).
 */

export interface QueryParamSpec {
  t: string;
  e?: (string | number)[];
  r?: 1;
}

export interface OperationSpec {
  p?: string[];
  q?: Record<string, QueryParamSpec>;
}

export const OPERATIONS: Record<string, OperationSpec> = {
  "GET /Tools/bookkeepingSystemVersion": {},
  "GET /CheckAccount": {},
  "POST /CheckAccount/Factory/fileImportAccount": {},
  "POST /CheckAccount/Factory/clearingAccount": {},
  "GET /CheckAccount/{checkAccountId}": {p:["checkAccountId"]},
  "PUT /CheckAccount/{checkAccountId}": {p:["checkAccountId"]},
  "DELETE /CheckAccount/{checkAccountId}": {p:["checkAccountId"]},
  "GET /CheckAccount/{checkAccountId}/getBalanceAtDate": {p:["checkAccountId"],q:{"date":{t:"string",r:1}}},
  "GET /CheckAccountTransaction": {q:{"checkAccount[id]":{t:"integer"},"checkAccount[objectName]":{t:"string"},"isBooked":{t:"boolean"},"paymtPurpose":{t:"string"},"startDate":{t:"string"},"endDate":{t:"string"},"payeePayerName":{t:"string"},"onlyCredit":{t:"boolean"},"onlyDebit":{t:"boolean"}}},
  "POST /CheckAccountTransaction": {},
  "GET /CheckAccountTransaction/{checkAccountTransactionId}": {p:["checkAccountTransactionId"]},
  "PUT /CheckAccountTransaction/{checkAccountTransactionId}": {p:["checkAccountTransactionId"]},
  "DELETE /CheckAccountTransaction/{checkAccountTransactionId}": {p:["checkAccountTransactionId"]},
  "PUT /CheckAccountTransaction/{checkAccountTransactionId}/enshrine": {p:["checkAccountTransactionId"]},
  "GET /Contact/Factory/getNextCustomerNumber": {},
  "GET /Contact/Factory/findContactsByCustomFieldValue": {q:{"value":{t:"string",r:1},"customFieldSetting[id]":{t:"string"},"customFieldSetting[objectName]":{t:"string"},"customFieldName":{t:"string",r:1}}},
  "GET /Contact/Mapper/checkCustomerNumberAvailability": {q:{"customerNumber":{t:"string"}}},
  "GET /Contact": {q:{"depth":{t:"string",e:["0","1"]},"customerNumber":{t:"string"}}},
  "POST /Contact": {},
  "GET /Contact/{contactId}": {p:["contactId"]},
  "PUT /Contact/{contactId}": {p:["contactId"]},
  "DELETE /Contact/{contactId}": {p:["contactId"]},
  "GET /Contact/{contactId}/getTabsItemCount": {p:["contactId"]},
  "POST /ContactAddress": {},
  "GET /ContactAddress": {},
  "GET /ContactAddress/{contactAddressId}": {p:["contactAddressId"]},
  "PUT /ContactAddress/{contactAddressId}": {p:["contactAddressId"]},
  "DELETE /ContactAddress/{contactAddressId}": {p:["contactAddressId"]},
  "GET /CommunicationWay": {q:{"contact[id]":{t:"string"},"contact[objectName]":{t:"string"},"type":{t:"string",e:["PHONE","EMAIL","WEB","MOBILE"]},"main":{t:"string",e:["0","1"]}}},
  "POST /CommunicationWay": {},
  "GET /CommunicationWay/{communicationWayId}": {p:["communicationWayId"]},
  "DELETE /CommunicationWay/{communicationWayId}": {p:["communicationWayId"]},
  "PUT /CommunicationWay/{communicationWayId}": {p:["communicationWayId"]},
  "GET /CommunicationWayKey": {},
  "GET /AccountingContact": {q:{"contact[id]":{t:"string"},"contact[objectName]":{t:"string"}}},
  "POST /AccountingContact": {},
  "GET /AccountingContact/{accountingContactId}": {p:["accountingContactId"]},
  "PUT /AccountingContact/{accountingContactId}": {p:["accountingContactId"]},
  "DELETE /AccountingContact/{accountingContactId}": {p:["accountingContactId"]},
  "GET /Textparser/fetchDictionaryEntriesByType": {q:{"objectName":{t:"string",e:["Invoice","CreditNote","Order","Contact","Letter","Email"],r:1},"subObjectName":{t:"string",e:["Invoice","CreditNote","Order","Contact","Letter"]}}},
  "GET /ContactCustomField": {},
  "POST /ContactCustomField": {},
  "GET /ContactCustomField/{contactCustomFieldId}": {p:["contactCustomFieldId"]},
  "PUT /ContactCustomField/{contactCustomFieldId}": {p:["contactCustomFieldId"]},
  "DELETE /ContactCustomField/{contactCustomFieldId}": {p:["contactCustomFieldId"]},
  "GET /ContactCustomFieldSetting": {},
  "POST /ContactCustomFieldSetting": {},
  "GET /ContactCustomFieldSetting/{contactCustomFieldSettingId}": {p:["contactCustomFieldSettingId"]},
  "PUT /ContactCustomFieldSetting/{contactCustomFieldSettingId}": {p:["contactCustomFieldSettingId"]},
  "DELETE /ContactCustomFieldSetting/{contactCustomFieldSettingId}": {p:["contactCustomFieldSettingId"]},
  "GET /ContactCustomFieldSetting/{contactCustomFieldSettingId}/getReferenceCount": {p:["contactCustomFieldSettingId"]},
  "GET /CreditNote": {q:{"status":{t:"string",e:["100","200","300","500","750","1000"]},"creditNoteNumber":{t:"string"},"startDate":{t:"integer"},"endDate":{t:"integer"},"contact[id]":{t:"integer"},"contact[objectName]":{t:"string"}}},
  "POST /CreditNote/Factory/saveCreditNote": {},
  "POST /CreditNote/Factory/createFromInvoice": {},
  "POST /CreditNote/Factory/createFromVoucher": {},
  "GET /CreditNote/{creditNoteId}": {p:["creditNoteId"]},
  "PUT /CreditNote/{creditNoteId}": {p:["creditNoteId"]},
  "DELETE /CreditNote/{creditNoteId}": {p:["creditNoteId"]},
  "GET /CreditNote/{creditNoteId}/sendByWithRender": {p:["creditNoteId"],q:{"sendType":{t:"string",r:1}}},
  "PUT /CreditNote/{creditNoteId}/sendBy": {p:["creditNoteId"]},
  "PUT /CreditNote/{creditNoteId}/enshrine": {p:["creditNoteId"]},
  "GET /CreditNote/{creditNoteId}/getPdf": {p:["creditNoteId"],q:{"download":{t:"boolean"},"preventSendBy":{t:"boolean"}}},
  "POST /CreditNote/{creditNoteId}/sendViaEmail": {p:["creditNoteId"]},
  "PUT /CreditNote/{creditNoteId}/bookAmount": {p:["creditNoteId"]},
  "PUT /CreditNote/{creditNoteId}/resetToOpen": {p:["creditNoteId"]},
  "PUT /CreditNote/{creditNoteId}/resetToDraft": {p:["creditNoteId"]},
  "GET /CreditNotePos": {q:{"creditNote[id]":{t:"integer"},"creditNote[objectName]":{t:"string"}}},
  "PUT /SevClient/{SevClientId}/updateExportConfig": {p:["SevClientId"]},
  "GET /Export/datevCSV": {q:{"Download":{t:"boolean"},"startDate":{t:"integer",r:1},"endDate":{t:"integer",r:1},"scope":{t:"string",r:1},"withUnpaidDocuments":{t:"boolean"},"withEnshrinedDocuments":{t:"boolean"},"enshrine":{t:"boolean"}}},
  "GET /Export/createDatevCsvZipExportJob": {q:{"startDate":{t:"integer",r:1},"endDate":{t:"integer",r:1},"scope":{t:"string",r:1},"exportByPaydate":{t:"boolean"},"includeEnshrined":{t:"boolean"},"enshrineDocuments":{t:"boolean"},"includeDocumentImages":{t:"boolean"}}},
  "GET /Export/createDatevXmlZipExportJob": {q:{"startDate":{t:"integer",r:1},"endDate":{t:"integer",r:1},"scope":{t:"string",r:1},"exportByPaydate":{t:"boolean"},"includeEnshrined":{t:"boolean"},"includeExportedDocuments":{t:"boolean"},"includeDocumentXml":{t:"boolean"}}},
  "GET /Progress/generateDownloadHash": {q:{"jobId":{t:"string",r:1}}},
  "GET /Progress/getProgress": {q:{"hash":{t:"string",r:1}}},
  "GET /ExportJob/jobDownloadInfo": {q:{"jobId":{t:"string",r:1}}},
  "GET /Export/invoiceCsv": {q:{"download":{t:"boolean"},"sevQuery":{t:"object",r:1}}},
  "GET /Export/invoiceZip": {q:{"download":{t:"boolean"},"sevQuery":{t:"object",r:1}}},
  "GET /Export/creditNoteCsv": {q:{"download":{t:"boolean"},"sevQuery":{t:"object",r:1}}},
  "GET /Export/voucherListCsv": {q:{"download":{t:"boolean"},"sevQuery":{t:"object",r:1}}},
  "GET /Export/transactionsCsv": {q:{"download":{t:"boolean"},"sevQuery":{t:"object",r:1}}},
  "GET /Export/voucherZip": {q:{"download":{t:"boolean"},"sevQuery":{t:"object",r:1}}},
  "GET /Export/contactListCsv": {q:{"download":{t:"boolean"},"sevQuery":{t:"object",r:1}}},
  "GET /Part": {q:{"partNumber":{t:"string"},"name":{t:"string"}}},
  "POST /Part": {},
  "GET /Part/{partId}": {p:["partId"]},
  "PUT /Part/{partId}": {p:["partId"]},
  "GET /Part/{partId}/getStock": {p:["partId"]},
  "GET /Invoice": {q:{"status":{t:"number",e:[100,200,1000]},"invoiceNumber":{t:"string"},"startDate":{t:"integer"},"endDate":{t:"integer"},"contact[id]":{t:"integer"},"contact[objectName]":{t:"string"}}},
  "POST /Invoice/Factory/saveInvoice": {},
  "GET /Invoice/{invoiceId}": {p:["invoiceId"]},
  "GET /Invoice/{invoiceId}/getPositions": {p:["invoiceId"],q:{"limit":{t:"integer"},"offset":{t:"integer"},"embed":{t:"array"}}},
  "POST /Invoice/Factory/createInvoiceFromOrder": {},
  "POST /Invoice/Factory/createInvoiceReminder": {q:{"invoice[id]":{t:"integer",r:1},"invoice[objectName]":{t:"string",r:1}}},
  "GET /Invoice/{invoiceId}/getIsPartiallyPaid": {p:["invoiceId"]},
  "POST /Invoice/{invoiceId}/cancelInvoice": {p:["invoiceId"]},
  "POST /Invoice/{invoiceId}/render": {p:["invoiceId"]},
  "POST /Invoice/{invoiceId}/sendViaEmail": {p:["invoiceId"]},
  "GET /Invoice/{invoiceId}/getPdf": {p:["invoiceId"],q:{"download":{t:"boolean"},"preventSendBy":{t:"boolean"}}},
  "GET /Invoice/{invoiceId}/getXml": {p:["invoiceId"]},
  "PUT /Invoice/{invoiceId}/sendBy": {p:["invoiceId"]},
  "PUT /Invoice/{invoiceId}/enshrine": {p:["invoiceId"]},
  "PUT /Invoice/{invoiceId}/bookAmount": {p:["invoiceId"]},
  "PUT /Invoice/{invoiceId}/resetToOpen": {p:["invoiceId"]},
  "PUT /Invoice/{invoiceId}/resetToDraft": {p:["invoiceId"]},
  "GET /InvoicePos": {q:{"id":{t:"number"},"invoice[id]":{t:"number"},"invoice[objectName]":{t:"string"},"part[id]":{t:"number"},"part[objectName]":{t:"string"}}},
  "GET /DocServer/getLetterpapersWithThumb": {},
  "GET /DocServer/getTemplatesWithThumb": {q:{"type":{t:"string",e:["Invoice","invoicereminder","Order","Contractnote","Packinglist","Letter","Creditnote"]}}},
  "PUT /Invoice/{invoiceId}/changeParameter": {p:["invoiceId"]},
  "PUT /Order/{orderId}/changeParameter": {p:["orderId"]},
  "PUT /CreditNote/{creditNoteId}/changeParameter": {p:["creditNoteId"]},
  "GET /Order": {q:{"status":{t:"integer",e:[100,200,300,500,750,1000]},"orderNumber":{t:"string"},"startDate":{t:"integer"},"endDate":{t:"integer"},"contact[id]":{t:"integer"},"contact[objectName]":{t:"string"}}},
  "POST /Order/Factory/saveOrder": {},
  "GET /Order/{orderId}": {p:["orderId"]},
  "PUT /Order/{orderId}": {p:["orderId"]},
  "DELETE /Order/{orderId}": {p:["orderId"]},
  "GET /Order/{orderId}/getPositions": {p:["orderId"],q:{"limit":{t:"integer"},"offset":{t:"integer"},"embed":{t:"array"}}},
  "GET /Order/{orderId}/getDiscounts": {p:["orderId"],q:{"limit":{t:"integer"},"offset":{t:"integer"},"embed":{t:"array"}}},
  "GET /Order/{orderId}/getRelatedObjects": {p:["orderId"],q:{"includeItself":{t:"boolean"},"sortByType":{t:"boolean"},"embed":{t:"array"}}},
  "POST /Order/{orderId}/sendViaEmail": {p:["orderId"]},
  "POST /Order/Factory/createPackingListFromOrder": {q:{"order[id]":{t:"integer",r:1},"order[objectName]":{t:"string",r:1}}},
  "POST /Order/Factory/createContractNoteFromOrder": {q:{"order[id]":{t:"integer",r:1},"order[objectName]":{t:"string",r:1}}},
  "GET /Order/{orderId}/getPdf": {p:["orderId"],q:{"download":{t:"boolean"},"preventSendBy":{t:"boolean"}}},
  "PUT /Order/{orderId}/sendBy": {p:["orderId"]},
  "GET /OrderPos": {q:{"order[id]":{t:"integer"},"order[objectName]":{t:"string"}}},
  "GET /OrderPos/{orderPosId}": {p:["orderPosId"]},
  "PUT /OrderPos/{orderPosId}": {p:["orderPosId"]},
  "DELETE /OrderPos/{orderPosId}": {p:["orderPosId"]},
  "POST /Voucher/Factory/saveVoucher": {},
  "POST /Voucher/Factory/uploadTempFile": {},
  "GET /Voucher": {q:{"status":{t:"number",e:[50,100,1000]},"creditDebit":{t:"string",e:["C","D"]},"descriptionLike":{t:"string"},"startDate":{t:"integer"},"endDate":{t:"integer"},"contact[id]":{t:"integer"},"contact[objectName]":{t:"string"}}},
  "GET /Voucher/{voucherId}": {p:["voucherId"]},
  "PUT /Voucher/{voucherId}": {p:["voucherId"]},
  "PUT /Voucher/{voucherId}/enshrine": {p:["voucherId"]},
  "PUT /Voucher/{voucherId}/bookAmount": {p:["voucherId"]},
  "PUT /Voucher/{voucherId}/resetToOpen": {p:["voucherId"]},
  "PUT /Voucher/{voucherId}/resetToDraft": {p:["voucherId"]},
  "GET /VoucherPos": {q:{"voucher[id]":{t:"integer"},"voucher[objectName]":{t:"string"}}},
  "GET /ReceiptGuidance/forAllAccounts": {},
  "GET /ReceiptGuidance/forAccountNumber": {q:{"accountNumber":{t:"integer",r:1}}},
  "GET /ReceiptGuidance/forTaxRule": {q:{"taxRule":{t:"string",r:1}}},
  "GET /ReceiptGuidance/forRevenue": {},
  "GET /ReceiptGuidance/forExpense": {},
  "GET /Report/invoicelist": {q:{"download":{t:"boolean"},"view":{t:"string",r:1},"sevQuery":{t:"object",r:1}}},
  "GET /Report/orderlist": {q:{"download":{t:"boolean"},"view":{t:"string",r:1},"sevQuery":{t:"object",r:1}}},
  "GET /Report/contactlist": {q:{"download":{t:"boolean"},"sevQuery":{t:"object",r:1}}},
  "GET /Report/voucherlist": {q:{"download":{t:"boolean"},"sevQuery":{t:"object",r:1}}},
  "GET /Tag": {q:{"id":{t:"number"},"name":{t:"string"}}},
  "GET /Tag/{tagId}": {p:["tagId"]},
  "PUT /Tag/{tagId}": {p:["tagId"]},
  "DELETE /Tag/{tagId}": {p:["tagId"]},
  "POST /Tag/Factory/create": {},
  "GET /TagRelation": {},
};
